//! Raw FFI bindings to the `auratokenizer` C++ library.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include the bindings generated by `bindgen`.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn linking_works() {
        // This test doesn't do much, but it's a compile-time check
        // to ensure that we can access a function from the C-API.
        // If this test compiles, it means bindgen has run correctly
        // and the Rust compiler can "see" the C functions.
        // A runtime test would require a valid model, which we'll
        // test in the higher-level safe crate.
        let func_pointer: Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char> =
            Some(aura_get_last_error_message);
        assert!(func_pointer.is_some());
    }
}
